### ISSUE TITLE
FacebookTokenError: This authorization code has been used.

### ISSUE THREAD

**Issue by arashdoescode** [sahat/hackathon-starter#323] opened 2015-09-27 09:39 UTC
There is an issue apparently with passport-facebook 
- https://github.com/HabitRPG/habitrpg/issues/4221

Whenever I try to login using facebook account it keeps loading and then it spits this error
FacebookTokenError: This authorization code has been used

Hope anyone could guide me upon this issue.

**Comment by sahat** [comment] 2015-09-27 22:51
@arashdoescode I don't have such issue and so couldn't reproduce this problem. I am going to close this since the issue seems to be with your Facebook app or passport-facebook, either way not something I could fix in the hackathon-starter project.

**Closed by sahat** 2015-09-27 22:51 UTC
