### ISSUE TITLE
Mongo DB errorDb.prototype.authenticate method will no longer be available

### ISSUE THREAD

**Issue by signaturr** [sahat/hackathon-starter#744] opened 2017-10-11 19:44 UTC
Should this be fixed?

## I got error in Terminal on Mac:
`Db.prototype.authenticate method will no longer be available`

## So I added
```js
,  { useMongoClient: true }
```

in app.js

```js
/**
 * Connect to MongoDB.
 */
mongoose.Promise = global.Promise;
// rob added , { useMongoClient: true } to get rid of error 
mongoose.connect(process.env.MONGODB_URI || process.env.MONGOLAB_URI,  { useMongoClient: true });

```

Thanks for a great starter tool

Rob

**Comment by YasharF** [comment] 2017-12-05 23:38
https://github.com/sahat/hackathon-starter/pull/738/files

**Comment by YasharF** [comment] 2017-12-05 23:39
https://github.com/sahat/hackathon-starter/pull/738

**Comment by YasharF** [comment] 2018-03-19 06:46
Duplicate of https://github.com/sahat/hackathon-starter/issues/739 ; the issue is not resolved because of an update to connect-mongo

**Closed by YasharF** 2018-03-19 06:46 UTC
