### ISSUE TITLE
live demo link on readme not working

### ISSUE THREAD

**Issue by jpca999** [sahat/hackathon-starter#678] opened 2017-04-08 04:47 UTC

**Comment by curran** [comment] 2017-04-10 11:10
More context (I think this is the same thing described in this issue) - when I access the following URL:

http://hackathonstarter-sahat.rhcloud.com/

I'm seeing the following error:

![image](https://cloud.githubusercontent.com/assets/68416/24859001/422c91ec-1e0c-11e7-953b-7a894a6c6fdd.png)

**Comment by curran** [comment] 2017-04-10 11:11
Duplicate of #673, should be closed probably.

**Closed** 2017-06-25 21:51 UTC
