### ISSUE TITLE
Add editorConfig to project

### ISSUE THREAD

**Issue by andela-rekemezie** [sahat/hackathon-starter#601] opened 2016-10-20 18:45 UTC
To keep indentation and formatting across all editors same, we need this issue to be fixed.

**Comment by niallobrien** [comment] 2016-10-21 09:42
@andela-rekemezie Agreed. I personally recommend ESlint and I'm guessing this project would be close to [Airbnb's ES6 Style Guide](https://github.com/airbnb/javascript) which we could enforce with their [eslint config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) as opposed to using something like [StandardJS](http://standardjs.com/) and its [eslint-config](https://github.com/feross/eslint-config-standard), though I do personally prefer StandardJS.

**Comment by YasharF** [comment] 2016-10-25 01:47
I personally use MS VS Code ( https://code.visualstudio.com ) and haven't had any issues.  My 2 cents is not to add too much to the base of the project, to reduce potential confusion for newcomers.  Many people at Hackathons that I have been to didn't have a whole lot of experienceS   Wimpler the project and number of the files that they have to deal with, the easier to ramp them up in the short time during the event.
Even the MVC model and split of the files sometimes causes a few hours of having to explain things to newcomers to ramp them up, which I rather not have to deal with when people already have to stay up over night to get something together for the demo.

**Comment by sahat** [comment] 2016-10-28 08:36
Closing as a duplicate of https://github.com/sahat/hackathon-starter/pull/499.

Editor-related stuff should be handled by your editor. I strongly encourage to have ESLint and Editorconfig with your settings and preferences in your projects, but it's not something I'd like to dictate with Hackathon Starter in particular. 

As @YasharF pointed out, less files means less headache for newcomers.

**Closed by sahat** 2016-10-28 08:36 UTC

**Comment by niallobrien** [comment] 2016-10-28 08:38
Does having an ESlint config file necessarily dictate anything? I mean, it could be ignored by most new-comers, but those wanting it will already have it...

**Comment by sahat** [comment] 2016-10-28 09:28
@niallobrien In my last reply, I justified that conclusion because I wasn't liking the idea of having `.eslintrc` and `.editorconfig` files at the root. On a related note, thinking about what I just said, this project is already pretty opinionated in that it has been using AirBnb style guide since the beginning, it was just never enforced via linters.

Then I remembered you can embed eslint config inside package.json. It would add about 3 lines of code for a very minimal, optional eslint configuration. I may have to add a few reasonable rule overrides to avoid re-wrtiting a bunch of code for the sake linting rules.

**package.json**
```
"eslintConfig": {
  "extends": "airbnb-base"
}
```

This is not too bad at all. And if you are using Webstorm IDE (not sure about Atom or Sublime), it will automatically detect ESLint config in your package.json.

**Comment by niallobrien** [comment] 2016-10-28 09:39
@sahat That would be a fair compromise. :+1:
