### ISSUE TITLE
Steam login issues

### ISSUE THREAD

**Issue by zippy4** [sahat/hackathon-starter#676] opened 2017-03-29 21:40 UTC
Hello, I am trying to login with steam localhost:300/auth/steam. It will redirect me to the steam login page and everything but when I get back it still wants me to make an account or login via another method.
It even added the information into the database but just won't let me login:
[https://gyazo.com/7fc83025f009f3e053b644cc9eda4a3f](https://gyazo.com/7fc83025f009f3e053b644cc9eda4a3f)

**Comment by YasharF** [comment] 2017-07-16 20:11
Duplicate of https://github.com/sahat/hackathon-starter/issues/600

**Closed** 2018-03-19 03:30 UTC
