### ISSUE TITLE
learn this item,which node version should be used?

### ISSUE THREAD

**Issue by feng003** [sahat/hackathon-starter#400] opened 2016-03-10 01:17 UTC
I use this item,encounter a question.

Error: The `libsass` binding was not found in /usr/share/nginx/mean/node_modules/node-sass-middleware/node_modules/node-sass/vendor/linux-x64-14/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

**Comment by feng003** [comment] 2016-03-10 01:18
I use the node version 0.12.10.

**Comment by sahat** [comment] 2016-03-14 19:47
Duplicate of:
1. https://github.com/sahat/hackathon-starter/issues/334
2. https://github.com/sahat/hackathon-starter/issues/327

**Closed by sahat** 2016-03-14 19:47 UTC
Labels: duplicate
