### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by marcospgp** [sahat/hackathon-starter#816] opened 2018-04-01 13:54 UTC
The solution in `app.js` for error handling is:

```
/**
 * Error Handler.
 */
app.use(errorHandler());
```

But the `errorhandler` package is listed as development only.

I could submit a pull request changing the error handler lines to:

```
/**
 * Error Handler.
 */
if (process.env.NODE_ENV === 'development') {
  // only use in development
  app.use(errorhandler());
}
```
as is suggested on the [package's readme](https://www.npmjs.com/package/errorhandler), but I suppose a solution should also be found for error handling in a production environment.

Cheers!

**Comment by YasharF** [comment] 2018-04-02 01:03
Duplicate of https://github.com/sahat/hackathon-starter/issues/703 ?

**Closed** 2018-04-02 16:25 UTC
