### ISSUE TITLE
Brave browser blocks the cookieconsent

### ISSUE THREAD

**Issue by vimark1** [sahat/hackathon-starter#1254] opened 2023-08-30 11:03 UTC
> Uncaught TypeError: Cannot read properties of undefined (reading 'initialise')

Brave blocks the cookieconsent url. We should check wether cookieconsent is available before attempting to use it.

<img width="1624" alt="image" src="https://github.com/sahat/hackathon-starter/assets/44329742/209c6c38-5bca-41c8-8ae8-a0491b2662c3">

**Comment by YasharF** [comment] 2023-09-09 16:44
Won't fix as it is with an unsupported web browsers that does not render pages as they were designed by site developers.  https://brave.com/privacy-updates/21-blocking-cookie-notices

Please use a popular web browsers such as Chrome, Firefox, or Edge that properly render websites as intended.

**Closed by YasharF** 2023-09-09 16:44 UTC
