### ISSUE TITLE
How to start.

### ISSUE THREAD

**Issue by emily0604** [sahat/hackathon-starter#763] opened 2017-11-20 14:55 UTC
I run `node app.js` but it has error 
```
node_modules/twilio/lib/rest/Twilio.js:126
    throw new Error('username is required');
```

could you help me ?

**Comment by thaibeouu** [comment] 2017-11-24 14:33
Check the `dotenv` init in your `app.js`, should be something like `dotenv.load({ path: '.env' });` and make sure the `.env` file is in the root of your project.

**Comment by some81** [comment] 2017-12-03 04:46
I'm running into the same issue. I checked everything and no any success

**Comment by YasharF** [comment] 2017-12-05 08:11
Are you using the .env.example that came with the project, or are you using your own .env file?
Also, what OS are you on?  Windows CMD, Win10 WSL, Mac, Linux?

**Comment by marcospgp** [comment] 2018-01-25 22:58
Same here, using .env.example that came with the project

**Comment by YasharF** [comment] 2018-01-26 18:11
It looks like that twilio now requires a valid username passed to it inorder for its npm module to load.  One workaround would be to create a twilio account and set TWILIO_SID to your own instead of the dummy ID  in the .env.example file.  TWILIO_TOKEN still doesn't have to be valid for the module to load.

**Comment by YasharF** [comment] 2018-01-26 18:34
Found the issue; it is not that a fully valid SID is required, but their npm module is checking for a format at https://github.com/twilio/twilio-node/blob/97f9db714286b3ebe70e406f532342b15b909717/lib/rest/Twilio.js#L133 to see if the first two letters of the SID are "AC". `TWILIO_SID=ACfake` is just enough to get it to work.

**Comment by niallobrien** [comment] 2018-01-26 18:36
Awesome, can we get a PR for this?

**Comment by YasharF** [comment] 2018-01-26 19:57
Scrap my prior notes (I deleted them).  Here is my finding.  In short I suspect that either your .env.example file is not loading or that there is already an _invalid_ TWILIO_SID set in your shell's environment variables.  If you have verified that you don't have an existing environment variable set (aka with `printenv` in bash or  `set` in cmd) then I would suggest:

Checking to see what is loaded from NodeJS's perspective at runtime; you can do this debugging by adding a console.log statement at the very top of api.js (on line 1): A line like `console.log('Checking TWILIO_SID: ', process.env.TWILIO_SID)`. Then see if you are getting a _valid_ TWILIO_SID at runtime before the error.



--- investigation notes from my end; adding this for anyone that saw my already deleted posts and is confused about what happened ---
I did two attempts to reproduce this problem starting from a clone, since it wasn't happening in my production environment.
First attempt failed, and I think it was because I had a dirty environment.  I personally usually don't use .env files and instead have the env variables set using the command prompt.  I suspect the failure was because I had run `export TWILIO_SID=fake` in my ubuntu shell.  Then I changed that line to one with my production SID and it worked.  Afterward I found that twilio's npm module https://github.com/twilio/twilio-node/blob/97f9db714286b3ebe70e406f532342b15b909717/lib/rest/Twilio.js#L133 is doing a check that the TWILIO_SID has to start with letters AC.  I tried `TWILIO_SID=ACfake` instead of my production SID and that worked as well, but then I realized that .env.example already has a TWILIO_SID that starts with the letters AC https://github.com/sahat/hackathon-starter/blob/master/.env.example#L38.
So, then I made my second attempt by closing all the shells and deleting my first clone, and then starting with another blank clone, and just following the readme instructions https://github.com/sahat/hackathon-starter#getting-started .  It worked out of the box.

```
:~$ cd /mnt/c/temp
:/mnt/c/temp$ git clone --depth=1 https://github.com/sahat/hackathon-starter.git myproject
Cloning into 'myproject'...
remote: Counting objects: 206, done.
remote: Compressing objects: 100% (202/202), done.
remote: Total 206 (delta 3), reused 143 (delta 1), pack-reused 0
Receiving objects: 100% (206/206), 795.95 KiB | 0 bytes/s, done.
Resolving deltas: 100% (3/3), done.
Checking connectivity... done.
:/mnt/c/temp$ cd myproject
:/mnt/c/temp/myproject$ npm install

> uws@0.14.5 install /mnt/c/temp/myproject/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> node-sass@4.5.3 install /mnt/c/temp/myproject/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/user/.npm/node-sass/4.5.3/linux-x64-57_binding.node

> node-sass@4.5.3 postinstall /mnt/c/temp/myproject/node_modules/node-sass
> node scripts/build.js

Binary found at /mnt/c/temp/myproject/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine

> hackathon-starter@4.3.0 postinstall /mnt/c/temp/myproject
> npm rebuild node-sass


> node-sass@4.5.3 install /mnt/c/temp/myproject/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /mnt/c/temp/myproject/node_modules/node-sass/vendor/linux-x64-57/binding.node

> node-sass@4.5.3 postinstall /mnt/c/temp/myproject/node_modules/node-sass
> node scripts/build.js

Binary found at /mnt/c/temp/myproject/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
node-sass@4.5.3 /mnt/c/temp/myproject/node_modules/node-sass
added 663 packages in 85.708s
:/mnt/c/temp/myproject$ node app.js
(node:322) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
✓ App is running at http://localhost:8080 in development mode
  Press CTRL-C to stop
```

**Comment by marcospgp** [comment] 2018-01-27 16:19
Apparently the confusion here seems to be that dotenv is loading the file named ".env.example"

**Comment by marcospgp** [comment] 2018-01-27 16:43
Oh, right. The line on app.js that loads dotenv is `dotenv.load({ path: '.env.example' });`. I assumed it was loading a file named .env by default.

I checked the line above, `const dotenv = require('dotenv');`, and assumed there was no configuration being done and thus the .env default was in use. My bad.

**Closed** 2018-03-19 03:32 UTC

**Comment by mayeaux** [comment] 2022-12-11 21:43
Still happening

**Comment by plakxj** [comment] 2022-12-11 21:44
收到！
