### ISSUE TITLE
lib-sass binding

### ISSUE THREAD

**Issue by mroknich** [sahat/hackathon-starter#327] opened 2015-10-03 03:47 UTC
Error: The `libsass` binding was not found in /Users/.../Documents/Projects/.../node_modules/node-sass-middleware/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

Tried running above command, so success. 

Any ideas?

**Comment by KevinBusse** [comment] 2015-10-06 08:33
Looks like a sub dependency is not build correctly, I'm guessing you upgraded your OS X, so you'll have to rebuild all binaries, try `npm rebuild` instead.

**Comment by jayhuang75** [comment] 2015-10-11 02:17
I have the same problem. Any idea or any fix for this? My node version is 4.1.1

**Comment by raunaqrox** [comment] 2015-10-11 02:34
I separately downloaded node-sass and it worked.
npm i node-sass

**Comment by jayhuang75** [comment] 2015-10-11 17:32
Thanks for your answer, but i still have the same problem.
 The `libsass` binding was not found in /xxxx/hackatonStarterKit/node_modules/node-sass-middleware/node_modules/node-sass/vendor/darwin-x64-46/binding.node

**Comment by sahat** [comment] 2015-10-11 21:13
@jayhuang75 Have you tried removing `node_modules` directory and reinstalling all packages again?

**Comment by jayhuang75** [comment] 2015-10-11 23:14
Hello Thank you so much for your reply! The steps I have been done!1. Sudo rm -rf node-‎modules2. Npm installWhich I still have the same problem.Thanks again                                                                                                                                                                                                                                                                                                                                        Best regards Wei Huang                                                                                                                                                                                                                From: Sahat YalkabovSent: Sunday, October 11, 2015 5:13 PMTo: sahat/hackathon-starterReply To: sahat/hackathon-starterCc: jayhuang75Subject: Re: [hackathon-starter] lib-sass binding (#327)@jayhuang75 Have you tried removing node_modules directory and reinstalling all packages again?

—Reply to this email directly or view it on GitHub.

**Comment by sahat** [comment] 2015-10-11 23:40
@jayhuang75 I am not sure what else could be causing this, other than perhaps a problem with your gcc compiler. I am not able to reproduce your issue on a Mac OS X 10.10 Yosemite with Xcode 7.0.1 + Command Line Tools. 

I have tried to reproduce the problem using both Node.js **0.12** and Node.js **4.0**. No issues.

**Comment by jayhuang75** [comment] 2015-10-13 13:53
@sahat Thank you for your reply, just curiosity, did you test in Node.js!

**Comment by sahat** [comment] 2015-10-19 17:35
@jayhuang75 Have you able to resolve this issue yet?

**Comment by jayhuang75** [comment] 2015-10-19 17:58
@sahat Yes, I downgrade my nodejs version then it works!
THX

**Comment by sahat** [comment] 2015-10-19 18:02
:+1:

**Closed by sahat** 2015-10-19 18:02 UTC
